Adding pr template and contributing guidlines for new contributors
devedmonton/DES-Website pull request #168
Opened 2023-07-28 16:14 UTC by MandyMeindersma

@Jhemming93

If this was here would your life been easier? Are there errors and cases I missed? Is this written well or should I reword anything?

2023-07-28 17:11 UTC, Jhemming93 requested changes

2023-07-28 17:11 UTC, Jhemming93 commented on .github/CONTRIBUTING.md
> +-   You might have to remove the single quotes in the `link-check` [file list](https://github.com/devedmonton/DES-Website/blob/main/package.json#L13). Just don't commit this change when you make your
ned to change "link-check" to "lint-check"

2023-07-28 17:11 UTC, Jhemming93 commented on .github/CONTRIBUTING.md
the only thing i might bring up is to format the code they edit or add with prettier, which will save them alot of headache with the linter

2023-07-28 17:30 UTC, MandyMeindersma commented on .github/CONTRIBUTING.md
added

2023-07-28 17:39 UTC, Jhemming93 approved these changes

2023-07-28 18:07 UTC, merged

2023-07-29 16:48 UTC, MandyMeindersma commented
@allcontributors add @Jhemming93 for review