Fix(#368): Rearranging Header
devedmonton/DES-Website pull request #382
Opened 2024-09-29 05:11 UTC by AACHAL2303PATIL

### *Description*
This pull request addresses issue *#368* by reorganizing the header and footer sections of our website.

### *Changes Made*
1. **Header Update**:
   - Removed the *Contacts* section from the header.
   - Replaced it with a new *Companies* section that links to the dedicated page.

2. **Footer Update**:
   - Added the *Contact* section back into the footer for easy access.

3. **Company Page**:
   - Created a dedicated page for the list of companies, sorted alphabetically.

### *Checklist*
- [x] Confirmed that the *Companies* section appears in the header.
- [x] Ensured that the *Contact* information is accessible in the footer.
- [x] Verified that the company list is alphabetized and displays correctly.

![Screenshot 2024-09-27 213148](https://github.com/user-attachments/assets/24fbcc71-c75d-45ef-a583-a95e47cb3ccf)
![Screenshot 2024-09-27 213211](https://github.com/user-attachments/assets/a8a37813-0502-44bb-ae93-718b77b942da)

2024-09-29 12:51 UTC, MandyMeindersma requested changes
So when I check the preview I am seeing that the comanies page isn't actually loading?

But if I hard refresh it does load:

![image](https://github.com/user-attachments/assets/ee112536-2032-4c2f-886b-cbc736bc2ca1)

2024-09-29 12:51 UTC, MandyMeindersma commented on constants/navigation.ts
> +    name: 'Companies', // Changed from 'Contact' to 'Companies'
you can remove these comments! Thank you :)

2024-09-29 13:21 UTC, AACHAL2303PATIL commented
I have made the necessary changes, and you can review them at your convenience.

2024-09-29 13:30 UTC, MandyMeindersma commented
hmmm I am still getting that error that the comanpies page isn't work right:
![image](https://github.com/user-attachments/assets/d6fc6931-3f4d-4f11-bf6b-a4f7acf0e328)

2024-09-29 13:31 UTC, MandyMeindersma commented
Also @AACHAL2303PATIL if you are going to do more open source contribution I would try to make your commits messages a little more descriptive rather than just the same message over and over again. It would help me review your code.

2024-10-02 05:45 UTC, AACHAL2303PATIL commented
The page is loading correctly in my browser. could you try opening it in an incognito tab?

![Screenshot 2024-10-02 111200](https://github.com/user-attachments/assets/e788ca55-1f83-4eac-9a44-7fdda6084f06)

2024-10-02 14:35 UTC, arashsheyda commented
@AACHAL2303PATIL the problem is if you navigate from another page to `/companies` it doesn't load.

2024-10-02 14:35 UTC, arashsheyda commented on pages/companies.vue
> +import { companies } from '@/constants/companies' // Adjust the path as necessary
you don't have to include the path as it is auto-imported

2024-10-02 14:41 UTC, AACHAL2303PATIL commented
Now check.

2024-10-02 14:48 UTC, arashsheyda commented
also could you add `defineOgImage` for SEO, you can check the `resources` page for reference

2024-10-02 14:51 UTC, AACHAL2303PATIL commented
Done check it.

2024-10-02 15:36 UTC, AACHAL2303PATIL commented
I HAVE MADE THE REQUIRED CHANGES. ANYTHING ELSE YOU WANT?

2024-10-02 16:04 UTC, MandyMeindersma commented
hey @AACHAL2303PATIL just as a heads up, when you use all caps it comes across really angry. If you are making more open source contributions I would avoid using all caps. 

We are all volunteers here so trying to keep things as positive as possible. 

In one of my first pr's I had over 75 comments on a pr. These comments really helped me be a better developer so it's something that everyone goes through :)

2024-10-02 16:08 UTC, MandyMeindersma commented
@AACHAL2303PATIL if you click the details tab in the build info you will be able to see the error @arashsheyda and I are seeing:

![image](https://github.com/user-attachments/assets/b7cbf0b9-04d1-41c5-8d0f-b45f46f35006)


Click details and then click "companies"

2024-10-02 16:10 UTC, MandyMeindersma commented
I think it might just be that you should put the template at the bottom of the file? Kind of like resources. If you try to make your new company file as similar to resources I think that would really help

2024-10-02 16:13 UTC, arashsheyda commented
@AACHAL2303PATIL thanks for your contribution! the code looks good to me

@MandyMeindersma I think the problem with the data not showing in the page might do something with the length of items (as we are using server components, I will take a look after work)

2024-10-13 13:32 UTC, MandyMeindersma commented
Since it has been 2 weeks since there has been any changes I am going to close this pr. Let me know if you want to still work on it and I can reassign you

2024-10-13 13:32 UTC, closed without merging